apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- digest: sha256:0e3149894dc86f5249dedcd46be7ab65d3fe26df8e433117d777b825c842b312
  name: hr
  newName: ghcr.io/redbadger/hr
- digest: sha256:a118837485f63bd96c603fdd2efef4875c55b7c32bce75f815c5c20d91259632
  name: slack
  newName: ghcr.io/redbadger/slack
resources:
- ../../bases/hr
- ../../bases/slack
