apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../bases/hr
  - ../../bases/slack

images:
- digest: sha256:9584fbcb56f312991c0118fba11ec7dbd66c1fee307f7eca1dfccf37283e07d7
  name: hr
  newName: ghcr.io/redbdager/hr
images:
- digest: sha256:63f6b4115727c2e921a9818bad0f1080754344d63f129323323aa457a34ce473
  name: slack
  newName: ghcr.io/redbdager/slack
