apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- digest: sha256:4b4aa2fa505128fb9b1610bd43d8c8765c65ef8bbe64d5a06c3ab367bc703cbd
  name: hr
  newName: ghcr.io/redbadger/hr
- digest: sha256:853ba6e11c15b2fc760892b4e8a1a05cf51445942c120121e8a3d2a27acef11c
  name: slack
  newName: ghcr.io/redbadger/slack
resources:
- ../../bases/hr
- ../../bases/slack
