apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- digest: sha256:edfca29e4e64c0ed0db9c78c129601a76af386146c1ff1ad52edb928e97b8bdc
  name: hr
  newName: ghcr.io/redbdager/hr
- digest: sha256:077028c6aed71647b3e654a3c2d67f87080f20b127f01cf12ec5c9e9edfe916a
  name: slack
  newName: ghcr.io/redbdager/slack
resources:
- ../../bases/hr
- ../../bases/slack
