apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- digest: sha256:9584fbcb56f312991c0118fba11ec7dbd66c1fee307f7eca1dfccf37283e07d7
  name: hr
  newName: ghcr.io/redbdager/hr
- digest: sha256:bd06ddae32140aec6dfb6e17840f7c47b0c086bda8de0d420ebea5b4e2a0aaf4
  name: slack
  newName: ghcr.io/redbdager/slack
resources:
- ../../bases/hr
- ../../bases/slack
