apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack
  labels:
    app: slack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: slack
  template:
    metadata:
      labels:
        app: slack
    spec:
      serviceAccountName: slack-sa
      containers:
        - name: slack
          image: ghcr.io/redbadger/slack
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
