# kubectl apply -f ./manifests/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-gateway-rules
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          # All access with the outside world must be via dapr
          # Currently slack is the only service we wish to expose
          # `slack`.slack is from `dapr.io/app-id` in deployment.yaml and slack.`slack` is the namespace
          - path: /v1.0/invoke/slack.slack/method/
            backend:
              serviceName: nginx-ingress-dapr
              servicePort: 80                
