apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr
  labels:
    app: hr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hr
  template:
    metadata:
      labels:
        app: hr
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "hr"
        dapr.io/app-port: "3000"
    spec:
      serviceAccountName: hr-sa
      containers:
        - name: hr
          image: ghcr.io/redbadger/hr:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
