apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack
  labels:
    app: slack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: slack
  template:
    metadata:
      labels:
        app: slack
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "slack"
        dapr.io/app-port: "3001"
    spec:
      serviceAccountName: slack-sa
      imagePullSecrets:
        - name: github-container-registry
      containers:
        - name: slack
          image: slack
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
